### ISSUE TITLE
Create mod Train tracks not render as curves

### ISSUE THREAD

**Issue by stacode123** [TeamJM/journeymap-lang#11]
![image](https://user-images.githubusercontent.com/49679054/200669346-9837d484-98c8-4867-857b-3f9086b1f6fe.png)
![image](https://user-images.githubusercontent.com/49679054/200669391-3bb799d4-99dd-46c0-aa9a-711f65afd542.png)
Here are some pictures.
thats all i have.
 create mod 5.0e and forge 1.18.2
 anything else ask me

**Comment by mysticdrew** [comment]
this has nothing to do with languages
